module.exports = {
  testEnvironment: "node",
  testMatch: ["**/tests/**/*.test.ts"],
  transform: {
    "^.+\\.ts$": ["ts-jest", { tsconfig: "tsconfig.base.json" }]
  },
  moduleNameMapper: {
    "^@stax/e2e-readiness$": "<rootDir>/packages/e2e-readiness/src/index.ts",
    "^@stax/commerce-billing$": "<rootDir>/packages/commerce-billing/src/index.ts",
    "^@stax/accounting-handoff$": "<rootDir>/packages/accounting-handoff/src/index.ts",
    "^@stax/fulfillment$": "<rootDir>/packages/fulfillment/src/index.ts",
    "^@stax/supplier-purchasing$": "<rootDir>/packages/supplier-purchasing/src/index.ts",
    "^@stax/payments$": "<rootDir>/packages/payments/src/index.ts",
    "^@stax/stripe-payments$": "<rootDir>/packages/stripe-payments/src/index.ts",
    "^@stax/quote-delivery$": "<rootDir>/packages/quote-delivery/src/index.ts",
    "^@stax/supplier-costs$": "<rootDir>/packages/supplier-costs/src/index.ts",
    "^@stax/margin-rules$": "<rootDir>/packages/margin-rules/src/index.ts",
    "^@stax/pricing-governance$": "<rootDir>/packages/pricing-governance/src/index.ts",
    "^@stax/quote-documents$": "<rootDir>/packages/quote-documents/src/index.ts",
    "^@stax/photo-quote-intake$": "<rootDir>/packages/photo-quote-intake/src/index.ts",
    "^@stax/c3-supply$": "<rootDir>/brands/c3-supply/src/index.ts",
    "^@stax/product-catalog$": "<rootDir>/packages/product-catalog/src/index.ts",
    "^@stax/cart$": "<rootDir>/packages/cart/src/index.ts",
    "^@stax/quote-workflow$": "<rootDir>/packages/quote-workflow/src/index.ts",
    "^@stax/orders$": "<rootDir>/packages/orders/src/index.ts",
    "^@stax/platform-hardening$": "<rootDir>/packages/platform-hardening/src/index.ts",
    "^@stax/deployment-switchboard$": "<rootDir>/packages/deployment-switchboard/src/index.ts",
    "^@stax/launch-readiness$": "<rootDir>/packages/launch-readiness/src/index.ts",
    "^@stax/storefront-conversion$": "<rootDir>/packages/storefront-conversion/src/index.ts",
    "^@stax/visual-system$": "<rootDir>/packages/visual-system/src/index.ts",
    "^@stax/authz$": "<rootDir>/packages/authz/src/index.ts",
    "^@stax/finance-export-ui$": "<rootDir>/packages/finance-export-ui/src/index.ts",
    "^@stax/accounting-export-storage$": "<rootDir>/packages/accounting-export-storage/src/index.ts",
    "^@stax/accounting-export$": "<rootDir>/packages/accounting-export/src/index.ts",
    "^@stax/customer-portal$": "<rootDir>/packages/customer-portal/src/index.ts",
    "^@stax/maintenance-plans$": "<rootDir>/packages/maintenance-plans/src/index.ts",
    "^@stax/notifications$": "<rootDir>/packages/notifications/src/index.ts",
    "^@stax/reporting$": "<rootDir>/packages/reporting/src/index.ts",
    "^@stax/service-billing$": "<rootDir>/packages/service-billing/src/index.ts",
    "^@stax/parts-inventory$": "<rootDir>/packages/parts-inventory/src/index.ts",
    "^@stax/core-contracts$": "<rootDir>/packages/core-contracts/src/index.ts",
    "^@stax/governance$": "<rootDir>/packages/governance/src/index.ts",
    "^@stax/audit$": "<rootDir>/packages/audit/src/index.ts",
    "^@stax/commands$": "<rootDir>/packages/commands/src/index.ts",
    "^@stax/workflows$": "<rootDir>/packages/workflows/src/index.ts",
    "^@stax/ai-support$": "<rootDir>/packages/ai-support/src/index.ts",
    "^@stax/service-interface$": "<rootDir>/packages/service-interface/src/index.ts",
    "^@stax/technician-portal$": "<rootDir>/packages/technician-portal/src/index.ts"
  }
};
